# Generated by Django 6.0.3 on 2026-03-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0002_rename_selfcarechecklist_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('individual', 'Individual Therapy'), ('group', 'Group Session'), ('assessment', 'Mental Health Assessment'), ('follow_up', 'Follow-Up Consultation'), ('crisis', 'Crisis Support')], default='individual', max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('therapist_name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, help_text="Clinic address or 'Online' for virtual sessions", max_length=200)),
                ('notes', models.TextField(blank=True, help_text="Any additional information or concerns you'd like to share")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['preferred_date', 'preferred_time'],
            },
        ),
    ]
