# Generated by Django 6.0.3 on 2026-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='daily_note',
            field=models.TextField(blank=True, default='', help_text='Optional reflection: how did this day feel?'),
        ),
    ]
