# Generated by Django 6.0.3 on 2026-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0004_checklist_daily_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed_date',
            field=models.DateField(blank=True, help_text='Actual confirmed date (may differ from preferred)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_time',
            field=models.TimeField(blank=True, help_text='Actual confirmed time', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Video call link (for video sessions)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_mode',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist_response',
            field=models.TextField(blank=True, help_text='Therapist or admin notes visible to the user after confirmation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Routine'), ('soon', 'Within a week'), ('urgent', 'Urgent — within 24–48 hours')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional information or concerns'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
