# Generated by Django 6.0.3 on 2026-03-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0005_appointment_confirmed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(default='Licensed Therapist', help_text='e.g. Clinical Psychologist, Counsellor', max_length=60)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapists/')),
                ('specialisation', models.CharField(choices=[('anxiety', 'Anxiety & Stress'), ('depression', 'Depression'), ('trauma', 'Trauma & PTSD'), ('relationships', 'Relationship Issues'), ('grief', 'Grief & Loss'), ('addiction', 'Addiction & Recovery'), ('youth', 'Youth & Adolescents'), ('crisis', 'Crisis Intervention'), ('general', 'General Mental Health')], default='general', max_length=30)),
                ('bio', models.TextField(blank=True, help_text='Short therapist bio shown on the booking page')),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('languages', models.CharField(default='English', help_text='Comma-separated, e.g. English, Swahili', max_length=200)),
                ('available_modes', models.CharField(default='in_person,video,phone', help_text='Comma-separated: in_person, video, phone', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('sessions_done', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('accepts_crisis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='therapist_name',
            field=models.CharField(blank=True, help_text='Manual override if therapist not in system', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mentalapp.therapist'),
        ),
    ]
